export const FETCH_CAPTCHA = 'FETCH_CAPTCHA'
export const CAPTCHATEXT_CHANGED = 'TEXT_CHANGED'
export const TRACKINGNUMBER_CHANGED = 'TRACKINGNUMBER_CHANGED'
export const SUBMIT_FORM = 'SUBMIT_FORM'
